//
// Created by root on 8/28/17.
//

#include "cpu.h"

void Cpu::opcode_cb0x00() {}
void Cpu::opcode_cb0x01() {}
void Cpu::opcode_cb0x02() {}
void Cpu::opcode_cb0x03() {}
void Cpu::opcode_cb0x04() {}
void Cpu::opcode_cb0x05() {}
void Cpu::opcode_cb0x06() {}
void Cpu::opcode_cb0x07() {}
void Cpu::opcode_cb0x08() {}
void Cpu::opcode_cb0x09() {}
void Cpu::opcode_cb0x0A() {}
void Cpu::opcode_cb0x0B() {}
void Cpu::opcode_cb0x0C() {}
void Cpu::opcode_cb0x0D() {}
void Cpu::opcode_cb0x0E() {}
void Cpu::opcode_cb0x0F() {}
void Cpu::opcode_cb0x10() {}
void Cpu::opcode_cb0x11() {}
void Cpu::opcode_cb0x12() {}
void Cpu::opcode_cb0x13() {}
void Cpu::opcode_cb0x14() {}
void Cpu::opcode_cb0x15() {}
void Cpu::opcode_cb0x16() {}
void Cpu::opcode_cb0x17() {}
void Cpu::opcode_cb0x18() {}
void Cpu::opcode_cb0x19() {}
void Cpu::opcode_cb0x1A() {}
void Cpu::opcode_cb0x1B() {}
void Cpu::opcode_cb0x1C() {}
void Cpu::opcode_cb0x1D() {}
void Cpu::opcode_cb0x1E() {}
void Cpu::opcode_cb0x1F() {}
void Cpu::opcode_cb0x20() {}
void Cpu::opcode_cb0x21() {}
void Cpu::opcode_cb0x22() {}
void Cpu::opcode_cb0x23() {}
void Cpu::opcode_cb0x24() {}
void Cpu::opcode_cb0x25() {}
void Cpu::opcode_cb0x26() {}
void Cpu::opcode_cb0x27() {}
void Cpu::opcode_cb0x28() {}
void Cpu::opcode_cb0x29() {}
void Cpu::opcode_cb0x2A() {}
void Cpu::opcode_cb0x2B() {}
void Cpu::opcode_cb0x2C() {}
void Cpu::opcode_cb0x2D() {}
void Cpu::opcode_cb0x2E() {}
void Cpu::opcode_cb0x2F() {}
void Cpu::opcode_cb0x30() {}
void Cpu::opcode_cb0x31() {}
void Cpu::opcode_cb0x32() {}
void Cpu::opcode_cb0x33() {}
void Cpu::opcode_cb0x34() {}
void Cpu::opcode_cb0x35() {}
void Cpu::opcode_cb0x36() {}
void Cpu::opcode_cb0x37() {}
void Cpu::opcode_cb0x38() {}
void Cpu::opcode_cb0x39() {}
void Cpu::opcode_cb0x3A() {}
void Cpu::opcode_cb0x3B() {}
void Cpu::opcode_cb0x3C() {}
void Cpu::opcode_cb0x3D() {}
void Cpu::opcode_cb0x3E() {}
void Cpu::opcode_cb0x3F() {}
void Cpu::opcode_cb0x40() {}
void Cpu::opcode_cb0x41() {}
void Cpu::opcode_cb0x42() {}
void Cpu::opcode_cb0x43() {}
void Cpu::opcode_cb0x44() {}
void Cpu::opcode_cb0x45() {}
void Cpu::opcode_cb0x46() {}
void Cpu::opcode_cb0x47() {}
void Cpu::opcode_cb0x48() {}
void Cpu::opcode_cb0x49() {}
void Cpu::opcode_cb0x4A() {}
void Cpu::opcode_cb0x4B() {}
void Cpu::opcode_cb0x4C() {}
void Cpu::opcode_cb0x4D() {}
void Cpu::opcode_cb0x4E() {}
void Cpu::opcode_cb0x4F() {}
void Cpu::opcode_cb0x50() {}
void Cpu::opcode_cb0x51() {}
void Cpu::opcode_cb0x52() {}
void Cpu::opcode_cb0x53() {}
void Cpu::opcode_cb0x54() {}
void Cpu::opcode_cb0x55() {}
void Cpu::opcode_cb0x56() {}
void Cpu::opcode_cb0x57() {}
void Cpu::opcode_cb0x58() {}
void Cpu::opcode_cb0x59() {}
void Cpu::opcode_cb0x5A() {}
void Cpu::opcode_cb0x5B() {}
void Cpu::opcode_cb0x5C() {}
void Cpu::opcode_cb0x5D() {}
void Cpu::opcode_cb0x5E() {}
void Cpu::opcode_cb0x5F() {}
void Cpu::opcode_cb0x60() {}
void Cpu::opcode_cb0x61() {}
void Cpu::opcode_cb0x62() {}
void Cpu::opcode_cb0x63() {}
void Cpu::opcode_cb0x64() {}
void Cpu::opcode_cb0x65() {}
void Cpu::opcode_cb0x66() {}
void Cpu::opcode_cb0x67() {}
void Cpu::opcode_cb0x68() {}
void Cpu::opcode_cb0x69() {}
void Cpu::opcode_cb0x6A() {}
void Cpu::opcode_cb0x6B() {}
void Cpu::opcode_cb0x6C() {}
void Cpu::opcode_cb0x6D() {}
void Cpu::opcode_cb0x6E() {}
void Cpu::opcode_cb0x6F() {}
void Cpu::opcode_cb0x70() {}
void Cpu::opcode_cb0x71() {}
void Cpu::opcode_cb0x72() {}
void Cpu::opcode_cb0x73() {}
void Cpu::opcode_cb0x74() {}
void Cpu::opcode_cb0x75() {}
void Cpu::opcode_cb0x76() {}
void Cpu::opcode_cb0x77() {}
void Cpu::opcode_cb0x78() {}
void Cpu::opcode_cb0x79() {}
void Cpu::opcode_cb0x7A() {}
void Cpu::opcode_cb0x7B() {}
void Cpu::opcode_cb0x7C() {}
void Cpu::opcode_cb0x7D() {}
void Cpu::opcode_cb0x7E() {}
void Cpu::opcode_cb0x7F() {}
void Cpu::opcode_cb0x80() {}
void Cpu::opcode_cb0x81() {}
void Cpu::opcode_cb0x82() {}
void Cpu::opcode_cb0x83() {}
void Cpu::opcode_cb0x84() {}
void Cpu::opcode_cb0x85() {}
void Cpu::opcode_cb0x86() {}
void Cpu::opcode_cb0x87() {}
void Cpu::opcode_cb0x88() {}
void Cpu::opcode_cb0x89() {}
void Cpu::opcode_cb0x8A() {}
void Cpu::opcode_cb0x8B() {}
void Cpu::opcode_cb0x8C() {}
void Cpu::opcode_cb0x8D() {}
void Cpu::opcode_cb0x8E() {}
void Cpu::opcode_cb0x8F() {}
void Cpu::opcode_cb0x90() {}
void Cpu::opcode_cb0x91() {}
void Cpu::opcode_cb0x92() {}
void Cpu::opcode_cb0x93() {}
void Cpu::opcode_cb0x94() {}
void Cpu::opcode_cb0x95() {}
void Cpu::opcode_cb0x96() {}
void Cpu::opcode_cb0x97() {}
void Cpu::opcode_cb0x98() {}
void Cpu::opcode_cb0x99() {}
void Cpu::opcode_cb0x9A() {}
void Cpu::opcode_cb0x9B() {}
void Cpu::opcode_cb0x9C() {}
void Cpu::opcode_cb0x9D() {}
void Cpu::opcode_cb0x9E() {}
void Cpu::opcode_cb0x9F() {}
void Cpu::opcode_cb0xA0() {}
void Cpu::opcode_cb0xA1() {}
void Cpu::opcode_cb0xA2() {}
void Cpu::opcode_cb0xA3() {}
void Cpu::opcode_cb0xA4() {}
void Cpu::opcode_cb0xA5() {}
void Cpu::opcode_cb0xA6() {}
void Cpu::opcode_cb0xA7() {}
void Cpu::opcode_cb0xA8() {}
void Cpu::opcode_cb0xA9() {}
void Cpu::opcode_cb0xAA() {}
void Cpu::opcode_cb0xAB() {}
void Cpu::opcode_cb0xAC() {}
void Cpu::opcode_cb0xAD() {}
void Cpu::opcode_cb0xAE() {}
void Cpu::opcode_cb0xAF() {}
void Cpu::opcode_cb0xB0() {}
void Cpu::opcode_cb0xB1() {}
void Cpu::opcode_cb0xB2() {}
void Cpu::opcode_cb0xB3() {}
void Cpu::opcode_cb0xB4() {}
void Cpu::opcode_cb0xB5() {}
void Cpu::opcode_cb0xB6() {}
void Cpu::opcode_cb0xB7() {}
void Cpu::opcode_cb0xB8() {}
void Cpu::opcode_cb0xB9() {}
void Cpu::opcode_cb0xBA() {}
void Cpu::opcode_cb0xBB() {}
void Cpu::opcode_cb0xBC() {}
void Cpu::opcode_cb0xBD() {}
void Cpu::opcode_cb0xBE() {}
void Cpu::opcode_cb0xBF() {}
void Cpu::opcode_cb0xC0() {}
void Cpu::opcode_cb0xC1() {}
void Cpu::opcode_cb0xC2() {}
void Cpu::opcode_cb0xC3() {}
void Cpu::opcode_cb0xC4() {}
void Cpu::opcode_cb0xC5() {}
void Cpu::opcode_cb0xC6() {}
void Cpu::opcode_cb0xC7() {}
void Cpu::opcode_cb0xC8() {}
void Cpu::opcode_cb0xC9() {}
void Cpu::opcode_cb0xCA() {}
void Cpu::opcode_cb0xCB() {}
void Cpu::opcode_cb0xCC() {}
void Cpu::opcode_cb0xCD() {}
void Cpu::opcode_cb0xCE() {}
void Cpu::opcode_cb0xCF() {}
void Cpu::opcode_cb0xD0() {}
void Cpu::opcode_cb0xD1() {}
void Cpu::opcode_cb0xD2() {}
void Cpu::opcode_cb0xD3() {}
void Cpu::opcode_cb0xD4() {}
void Cpu::opcode_cb0xD5() {}
void Cpu::opcode_cb0xD6() {}
void Cpu::opcode_cb0xD7() {}
void Cpu::opcode_cb0xD8() {}
void Cpu::opcode_cb0xD9() {}
void Cpu::opcode_cb0xDA() {}
void Cpu::opcode_cb0xDB() {}
void Cpu::opcode_cb0xDC() {}
void Cpu::opcode_cb0xDD() {}
void Cpu::opcode_cb0xDE() {}
void Cpu::opcode_cb0xDF() {}
void Cpu::opcode_cb0xE0() {}
void Cpu::opcode_cb0xE1() {}
void Cpu::opcode_cb0xE2() {}
void Cpu::opcode_cb0xE3() {}
void Cpu::opcode_cb0xE4() {}
void Cpu::opcode_cb0xE5() {}
void Cpu::opcode_cb0xE6() {}
void Cpu::opcode_cb0xE7() {}
void Cpu::opcode_cb0xE8() {}
void Cpu::opcode_cb0xE9() {}
void Cpu::opcode_cb0xEA() {}
void Cpu::opcode_cb0xEB() {}
void Cpu::opcode_cb0xEC() {}
void Cpu::opcode_cb0xED() {}
void Cpu::opcode_cb0xEE() {}
void Cpu::opcode_cb0xEF() {}
void Cpu::opcode_cb0xF0() {}
void Cpu::opcode_cb0xF1() {}
void Cpu::opcode_cb0xF2() {}
void Cpu::opcode_cb0xF3() {}
void Cpu::opcode_cb0xF4() {}
void Cpu::opcode_cb0xF5() {}
void Cpu::opcode_cb0xF6() {}
void Cpu::opcode_cb0xF7() {}
void Cpu::opcode_cb0xF8() {}
void Cpu::opcode_cb0xF9() {}
void Cpu::opcode_cb0xFA() {}
void Cpu::opcode_cb0xFB() {}
void Cpu::opcode_cb0xFC() {}
void Cpu::opcode_cb0xFD() {}
void Cpu::opcode_cb0xFE() {}
void Cpu::opcode_cb0xFF() {}
