//
// Created by root on 8/27/17.
//

#include "cpu.h"

void Cpu::opcode_0x00() {}
void Cpu::opcode_0x01() {}
void Cpu::opcode_0x02() {}
void Cpu::opcode_0x03() {}
void Cpu::opcode_0x04() {}
void Cpu::opcode_0x05() {}
void Cpu::opcode_0x06() {}
void Cpu::opcode_0x07() {}
void Cpu::opcode_0x08() {}
void Cpu::opcode_0x09() {}
void Cpu::opcode_0x0A() {}
void Cpu::opcode_0x0B() {}
void Cpu::opcode_0x0C() {}
void Cpu::opcode_0x0D() {}
void Cpu::opcode_0x0E() {}
void Cpu::opcode_0x0F() {}
void Cpu::opcode_0x10() {}
void Cpu::opcode_0x11() {}
void Cpu::opcode_0x12() {}
void Cpu::opcode_0x13() {}
void Cpu::opcode_0x14() {}
void Cpu::opcode_0x15() {}
void Cpu::opcode_0x16() {}
void Cpu::opcode_0x17() {}
void Cpu::opcode_0x18() {}
void Cpu::opcode_0x19() {}
void Cpu::opcode_0x1A() {}
void Cpu::opcode_0x1B() {}
void Cpu::opcode_0x1C() {}
void Cpu::opcode_0x1D() {}
void Cpu::opcode_0x1E() {}
void Cpu::opcode_0x1F() {}
void Cpu::opcode_0x20() {}
void Cpu::opcode_0x21() {}
void Cpu::opcode_0x22() {}
void Cpu::opcode_0x23() {}
void Cpu::opcode_0x24() {}
void Cpu::opcode_0x25() {}
void Cpu::opcode_0x26() {}
void Cpu::opcode_0x27() {}
void Cpu::opcode_0x28() {}
void Cpu::opcode_0x29() {}
void Cpu::opcode_0x2A() {}
void Cpu::opcode_0x2B() {}
void Cpu::opcode_0x2C() {}
void Cpu::opcode_0x2D() {}
void Cpu::opcode_0x2E() {}
void Cpu::opcode_0x2F() {}
void Cpu::opcode_0x30() {}
void Cpu::opcode_0x31() {}
void Cpu::opcode_0x32() {}
void Cpu::opcode_0x33() {}
void Cpu::opcode_0x34() {}
void Cpu::opcode_0x35() {}
void Cpu::opcode_0x36() {}
void Cpu::opcode_0x37() {}
void Cpu::opcode_0x38() {}
void Cpu::opcode_0x39() {}
void Cpu::opcode_0x3A() {}
void Cpu::opcode_0x3B() {}
void Cpu::opcode_0x3C() {}
void Cpu::opcode_0x3D() {}
void Cpu::opcode_0x3E() {}
void Cpu::opcode_0x3F() {}
void Cpu::opcode_0x40() {}
void Cpu::opcode_0x41() {}
void Cpu::opcode_0x42() {}
void Cpu::opcode_0x43() {}
void Cpu::opcode_0x44() {}
void Cpu::opcode_0x45() {}
void Cpu::opcode_0x46() {}
void Cpu::opcode_0x47() {}
void Cpu::opcode_0x48() {}
void Cpu::opcode_0x49() {}
void Cpu::opcode_0x4A() {}
void Cpu::opcode_0x4B() {}
void Cpu::opcode_0x4C() {}
void Cpu::opcode_0x4D() {}
void Cpu::opcode_0x4E() {}
void Cpu::opcode_0x4F() {}
void Cpu::opcode_0x50() {}
void Cpu::opcode_0x51() {}
void Cpu::opcode_0x52() {}
void Cpu::opcode_0x53() {}
void Cpu::opcode_0x54() {}
void Cpu::opcode_0x55() {}
void Cpu::opcode_0x56() {}
void Cpu::opcode_0x57() {}
void Cpu::opcode_0x58() {}
void Cpu::opcode_0x59() {}
void Cpu::opcode_0x5A() {}
void Cpu::opcode_0x5B() {}
void Cpu::opcode_0x5C() {}
void Cpu::opcode_0x5D() {}
void Cpu::opcode_0x5E() {}
void Cpu::opcode_0x5F() {}
void Cpu::opcode_0x60() {}
void Cpu::opcode_0x61() {}
void Cpu::opcode_0x62() {}
void Cpu::opcode_0x63() {}
void Cpu::opcode_0x64() {}
void Cpu::opcode_0x65() {}
void Cpu::opcode_0x66() {}
void Cpu::opcode_0x67() {}
void Cpu::opcode_0x68() {}
void Cpu::opcode_0x69() {}
void Cpu::opcode_0x6A() {}
void Cpu::opcode_0x6B() {}
void Cpu::opcode_0x6C() {}
void Cpu::opcode_0x6D() {}
void Cpu::opcode_0x6E() {}
void Cpu::opcode_0x6F() {}
void Cpu::opcode_0x70() {}
void Cpu::opcode_0x71() {}
void Cpu::opcode_0x72() {}
void Cpu::opcode_0x73() {}
void Cpu::opcode_0x74() {}
void Cpu::opcode_0x75() {}
void Cpu::opcode_0x76() {}
void Cpu::opcode_0x77() {}
void Cpu::opcode_0x78() {}
void Cpu::opcode_0x79() {}
void Cpu::opcode_0x7A() {}
void Cpu::opcode_0x7B() {}
void Cpu::opcode_0x7C() {}
void Cpu::opcode_0x7D() {}
void Cpu::opcode_0x7E() {}
void Cpu::opcode_0x7F() {}
void Cpu::opcode_0x80() {}
void Cpu::opcode_0x81() {}
void Cpu::opcode_0x82() {}
void Cpu::opcode_0x83() {}
void Cpu::opcode_0x84() {}
void Cpu::opcode_0x85() {}
void Cpu::opcode_0x86() {}
void Cpu::opcode_0x87() {}
void Cpu::opcode_0x88() {}
void Cpu::opcode_0x89() {}
void Cpu::opcode_0x8A() {}
void Cpu::opcode_0x8B() {}
void Cpu::opcode_0x8C() {}
void Cpu::opcode_0x8D() {}
void Cpu::opcode_0x8E() {}
void Cpu::opcode_0x8F() {}
void Cpu::opcode_0x90() {}
void Cpu::opcode_0x91() {}
void Cpu::opcode_0x92() {}
void Cpu::opcode_0x93() {}
void Cpu::opcode_0x94() {}
void Cpu::opcode_0x95() {}
void Cpu::opcode_0x96() {}
void Cpu::opcode_0x97() {}
void Cpu::opcode_0x98() {}
void Cpu::opcode_0x99() {}
void Cpu::opcode_0x9A() {}
void Cpu::opcode_0x9B() {}
void Cpu::opcode_0x9C() {}
void Cpu::opcode_0x9D() {}
void Cpu::opcode_0x9E() {}
void Cpu::opcode_0x9F() {}
void Cpu::opcode_0xA0() {}
void Cpu::opcode_0xA1() {}
void Cpu::opcode_0xA2() {}
void Cpu::opcode_0xA3() {}
void Cpu::opcode_0xA4() {}
void Cpu::opcode_0xA5() {}
void Cpu::opcode_0xA6() {}
void Cpu::opcode_0xA7() {}
void Cpu::opcode_0xA8() {}
void Cpu::opcode_0xA9() {}
void Cpu::opcode_0xAA() {}
void Cpu::opcode_0xAB() {}
void Cpu::opcode_0xAC() {}
void Cpu::opcode_0xAD() {}
void Cpu::opcode_0xAE() {}
void Cpu::opcode_0xAF() {}
void Cpu::opcode_0xB0() {}
void Cpu::opcode_0xB1() {}
void Cpu::opcode_0xB2() {}
void Cpu::opcode_0xB3() {}
void Cpu::opcode_0xB4() {}
void Cpu::opcode_0xB5() {}
void Cpu::opcode_0xB6() {}
void Cpu::opcode_0xB7() {}
void Cpu::opcode_0xB8() {}
void Cpu::opcode_0xB9() {}
void Cpu::opcode_0xBA() {}
void Cpu::opcode_0xBB() {}
void Cpu::opcode_0xBC() {}
void Cpu::opcode_0xBD() {}
void Cpu::opcode_0xBE() {}
void Cpu::opcode_0xBF() {}
void Cpu::opcode_0xC0() {}
void Cpu::opcode_0xC1() {}
void Cpu::opcode_0xC2() {}
void Cpu::opcode_0xC3() {}
void Cpu::opcode_0xC4() {}
void Cpu::opcode_0xC5() {}
void Cpu::opcode_0xC6() {}
void Cpu::opcode_0xC7() {}
void Cpu::opcode_0xC8() {}
void Cpu::opcode_0xC9() {}
void Cpu::opcode_0xCA() {}
void Cpu::opcode_0xCB() {}
void Cpu::opcode_0xCC() {}
void Cpu::opcode_0xCD() {}
void Cpu::opcode_0xCE() {}
void Cpu::opcode_0xCF() {}
void Cpu::opcode_0xD0() {}
void Cpu::opcode_0xD1() {}
void Cpu::opcode_0xD2() {}
void Cpu::opcode_0xD3() {}
void Cpu::opcode_0xD4() {}
void Cpu::opcode_0xD5() {}
void Cpu::opcode_0xD6() {}
void Cpu::opcode_0xD7() {}
void Cpu::opcode_0xD8() {}
void Cpu::opcode_0xD9() {}
void Cpu::opcode_0xDA() {}
void Cpu::opcode_0xDB() {}
void Cpu::opcode_0xDC() {}
void Cpu::opcode_0xDD() {}
void Cpu::opcode_0xDE() {}
void Cpu::opcode_0xDF() {}
void Cpu::opcode_0xE0() {}
void Cpu::opcode_0xE1() {}
void Cpu::opcode_0xE2() {}
void Cpu::opcode_0xE3() {}
void Cpu::opcode_0xE4() {}
void Cpu::opcode_0xE5() {}
void Cpu::opcode_0xE6() {}
void Cpu::opcode_0xE7() {}
void Cpu::opcode_0xE8() {}
void Cpu::opcode_0xE9() {}
void Cpu::opcode_0xEA() {}
void Cpu::opcode_0xEB() {}
void Cpu::opcode_0xEC() {}
void Cpu::opcode_0xED() {}
void Cpu::opcode_0xEE() {}
void Cpu::opcode_0xEF() {}
void Cpu::opcode_0xF0() {}
void Cpu::opcode_0xF1() {}
void Cpu::opcode_0xF2() {}
void Cpu::opcode_0xF3() {}
void Cpu::opcode_0xF4() {}
void Cpu::opcode_0xF5() {}
void Cpu::opcode_0xF6() {}
void Cpu::opcode_0xF7() {}
void Cpu::opcode_0xF8() {}
void Cpu::opcode_0xF9() {}
void Cpu::opcode_0xFA() {}
void Cpu::opcode_0xFB() {}
void Cpu::opcode_0xFC() {}
void Cpu::opcode_0xFD() {}
void Cpu::opcode_0xFE() {}
void Cpu::opcode_0xFF() {}